### ISSUE TITLE
How to store the result of the spdx command?

### ISSUE THREAD

**Issue by schmidtw** [fsfe/reuse-action#20]
I'd like to capture the output of the `spdx` command.  Do you have a way to either write it to a file or to an environment variable?

**Comment by mxmehl** [comment]
You could try passing the `-o` flag to the spdx subcommand which writes the output to a file:

```yaml
    - uses: actions/checkout@v3
    - name: REUSE SPDX SBOM
      uses: fsfe/reuse-action@v1
      with:
        args: spdx -o sbom.spdx
```

The file `sbom.spdx` should then be available in the workspace.
