### ISSUE TITLE
cmd is not required

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-action#3]
This issue is a bit of a mess as-written. Please forgive me.

```
inputs:
  cmd:
    description: 'Subcommand'
    required: true
    default: 'lint'
```

Because there is a default (i.e. fallback), is `cmd` required?

I think I would also sooner rename `cmd` to `args` (which appears more standard).

Also, the README says:

> Please note that due to Github restrictions it is not possible to pass extra arguments like `--include-submodules` to the `cmd` input.

Isn't it? You could simply do `args: --include-submodules lint`, no? Important to note, `args: lint --include-submodules` is invalid.
