### ISSUE TITLE
how to skip binary files?

### ISSUE THREAD

**Issue by yegor256** [fsfe/reuse-action#39]
I'm getting this:

```
# MISSING COPYRIGHT AND LICENSING INFORMATION

The following files have no copyright and licensing information:
* src/site/resources/favicon.ico
* src/site/resources/logo.png
```

What should I do about these files?

**Comment by yegor256** [comment]
I fixed it by adding `REUSE.toml` file to the root directory of my repo:

```toml
version = 1
[[annotations]]
path = [
     "src/site/resources/favicon.ico",
     "src/site/resources/logo.png"
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2013-2025 Yegor"
SPDX-License-Identifier = "MIT"
```
