### ISSUE TITLE
Error when downloading the action

### ISSUE THREAD

**Issue by jjtang1985** [fsfe/reuse-action#9]
Hi,
I've got an error:
```
Download action repository 'fsfe/reuse-action@v1'
##[error]An action could not be found at the URI 'https://api.github.com/repos/fsfe/reuse-action/tarball/v1'
```

Here is my `.yaml` file:
```
...
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: REUSE Compliance Check
         uses: fsfe/reuse-action@v1
...
```
